[package]
name = "oxford"
version = "0.0.1"
publish = false
authors = ["Matthew Palmer <mspalmer91@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
reqwest = "0.9.17"
serde = "1.0.91"
futures = "0.1.27"
tokio-core = "0.1.17"
